### ISSUE TITLE
bug: Agents provisioned as Servers

### ISSUE THREAD

**Issue by hutger** [lablabs/ansible-role-rke2#112]
### Summary

Hi There, 

I'm trying to expand an existent cluster that is formerly composed of 3x node performing Master/Worker node. 

I would like to expand the cluster by adding Worker-only nodes and for that I've got the following definitions:

Ansible runs fine, but in the all nodes are reported as control-plane nodes:

```
# kubectl get nodes -w
NAME       STATUS     ROLES                       AGE     VERSION
master-1   Ready      control-plane,etcd,master   7h54m   v1.22.10+rke2r2
master-2   Ready      control-plane,etcd,master   6h45m   v1.22.10+rke2r2
master-3   Ready      control-plane,etcd,master   6h50m   v1.22.10+rke2r2
worker-1   Ready      control-plane,etcd,master   90s     v1.22.10+rke2r2 
```

Am I doing something wrong or this can be a potential bug?

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.13.2]
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /root/.local/bin/ansible
  python version = 3.9.13 (main, Jun 10 2022, 09:50:06) [GCC]
  jinja version = 3.1.2
  libyaml = True
```

### Steps to Reproduce

_inventory.yaml_
```yaml
[masters]
master-1 ansible_host=master-1 rke2_type=server
master-2 ansible_host=master-2 rke2_type=server
master-3 ansible_host=master-3 rke2_type=server

[workers]
worker-1 ansible_host=worker-1 rke2_type=agent

[k8s_cluster:children]
masters
workers
```

_main.yaml_
```yaml
# Install RKE2
- name: RKE2 Setup on Cluster-wide
  hosts: k8s_cluster
  roles:
    - role: RKE2Cluster
```

vars.yaml
```yaml
---
# RKE2 Settings
os_privileged_group: gok8sadm
rke2_type: server
rke2_airgap_mode: false
rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_ha_mode_kubevip: true
rke2_api_ip: 192.168.86.100
rke2_interface: eth0
rke2_loadbalancer_ip_range: 192.168.86.101-192.168.86.105
rke2_kubevip_cloud_provider_enable: true
rke2_kubevip_svc_enable: true
rke2_additional_sans: [ my-k8s-dev.hutger.xyz ]
rke2_apiserver_dest_port: 6443
rke2_disable:
  - rke2-ingress-nginx
rke2_server_taint: false
rke2_token: my-token
rke2_version: v1.22.10+rke2r2
rke2_data_path: /var/lib/rancher/rke2
rke2_channel: stable
rke2_cni: canal
rke2_download_kubeconf: true
rke2_download_kubeconf_file_name: rke2.yaml
rke2_download_kubeconf_path: /tmp
rke2_servers_group_name: masters
rke2_agents_group_name: workers
``` 

### Expected Results

No roles associated to Worker-1 
```console
kubectl get nodes -w
NAME       STATUS     ROLES                       AGE     VERSION
master-1   Ready      control-plane,etcd,master   7h54m   v1.22.10+rke2r2
master-2   Ready      control-plane,etcd,master   6h45m   v1.22.10+rke2r2
master-3   Ready      control-plane,etcd,master   6h50m   v1.22.10+rke2r2
worker-1   Ready      <none>                                       90s     v1.22.10+rke2r2 
```

### Actual Results

Worker-1 being set as Master.

```console
kubectl get nodes -w
NAME       STATUS     ROLES                       AGE     VERSION
master-1   Ready      control-plane,etcd,master   7h54m   v1.22.10+rke2r2
master-2   Ready      control-plane,etcd,master   6h45m   v1.22.10+rke2r2
master-3   Ready      control-plane,etcd,master   6h50m   v1.22.10+rke2r2
worker-1   Ready      control-plane,etcd,master   90s     v1.22.10+rke2r2 
```
