### ISSUE TITLE
bug: Monitoring with Prometheus stack chart (can't get targets Etcd, Scheduler, Controller-manager )

### ISSUE THREAD

**Issue by aaktaev** [lablabs/ansible-role-rke2#114]
### Summary

I've installed rke2 with ansible, installed there prometheus-stack chart, in the targets  - etcd, Scheduler, Controller-manager can't be reached

![image](https://user-images.githubusercontent.com/12893205/200016525-68cd5fcf-7db6-431c-beb7-9d940a5302f3.png)

### Issue Type

Bug Report

### Ansible Version

```console
ansible 2.10.17
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.8/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]

```
```


### Steps to Reproduce

Install rke2. 
Install prmetheus-stack chart
Check targets for monitoring in prometheus


### Expected Results

All services are reachable

### Actual Results

```console
can't get targets Etcd, Scheduler, Controller-manager
```

**Comment by MonolithProjects** [comment]
HI @aaktaev i don't think that the issue you described is a bug of this Ansible Role. It looks more like a configuration issue. Scheduler nor control-manager does not expose their endpoints by default. Endpoint of etcd in RKE2 is also not exposed and you need to allow it by special option for rke2-server (i do not remember the name of that option but you can find int it RKE2 documentation). 

Btw if you want to change some default rke2-server option which is not represented in this Role as a separate variable, you can use [rke2_server_options](https://github.com/lablabs/ansible-role-rke2/blob/main/defaults/main.yml#L176) variable instead.

**Comment by jgoelen** [comment]
@aaktaev the problem is that the components you mention are only accessible via 127.0.0.1/locahost for security reasons. You probably want to use the rancher monitoring helm chart ... https://docs.ranchermanager.rancher.io/integrations-in-rancher/monitoring-and-alerting/how-monitoring-works

**Comment by aaktaev** [comment]
@jgoelen , Hi,

i'm wondering how can I expose f.e. kube-proxy to be able get metrics by Prometheus? (without using push proxy)

**Comment by jgoelen** [comment]
@aaktaev FYI: https://repo1.dso.mil/platform-one/big-bang/bigbang/-/issues/148

**Comment by aaktaev** [comment]
@jgoelen , seems that link is broken

**Comment by aaktaev** [comment]
Also, I do not need to get access to kube-proxy exactly, only set `metrics-bind-address: 0.0.0.0`

**Comment by aaktaev** [comment]
@MonolithProjects , how can I set `metrics-bind-address: 0.0.0.0` for kube-proxy to get metrics by prometheus?

**Comment by aaktaev** [comment]
https://github.com/rancher/rke2-charts/blob/53a28fdcc2ce5cd06ab530e632333c54ef7f497b/packages/rke2-kube-proxy/charts/templates/config.yaml#L49

**Comment by hoangphuocbk** [comment]
hi @jgoelen,
Do you have the example of values.yaml of rancher monitoring's helm chart? It's hard for me to find any document about kube-prometheus-stack's distro.

**Comment by jgoelen** [comment]
@hoangphuocbk we don't have a satisfying solution (yet 😁) for getting alerts for ETCD, kube-proxy, etc. Therefore we temporarily disabled the alerts.

We use the following Helm chart config:

Chart.yaml
```yaml
apiVersion: v2
appVersion: "1.0"
description: A Monitoring Helm chart for RKE2
name: monitoring
version: 0.1.0
dependencies:
    - name: kube-prometheus-stack
      version: "41.5.1"
      repository: "https://prometheus-community.github.io/helm-charts"
``` 

values.yaml
```yaml
kube-prometheus-stack:
  namespaceOverride: monitoring
  alertmanager:
    config:
      global:
        resolve_timeout: 5m
        slack_api_url: https://hooks.slack.com/services/******
      inhibit_rules:
        - source_matchers:
            - 'severity = critical'
          target_matchers:
            - 'severity =~ warning|info'
          equal:
            - 'namespace'
            - 'alertname'
        - source_matchers:
            - 'severity = warning'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
            - 'alertname'
        - source_matchers:
            - 'alertname = InfoInhibitor'
          target_matchers:
            - 'severity = info'
          equal:
            - 'namespace'
      route:
        group_by: ['namespace']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'null'
        routes:
        - receiver: 'null'
          matchers:
            - alertname =~ "InfoInhibitor|Watchdog"
        - match:
          receiver: 'slack'
          continue: true
      receivers:
      - name: 'null'
      - name: 'slack'
        slack_configs:
        - channel: '#dev-cluster-alerts'
          send_resolved: false
          title: 'DEV cluster [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Alert'
          text: >-
            {{ range .Alerts }}
              *Alert:* {{ .Annotations.summary }} - `{{ .Labels.severity }}`
              *Description:* {{ .Annotations.description }}
              *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
      templates:
      - '/etc/alertmanager/config/*.tmpl'
  grafana:
    namespaceOverride: monitoring
    admin:
      existingSecret: grafana-admin-secrets
    ingress:
      enabled: true
      hosts:
        - monitoring-dev.myorg.be
      tls:
        - hosts:
          - monitoring-dev.myorg.be
  prometheus-node-exporter:
    namespaceOverride: monitoring
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Exists
      - effect: NoExecute
        key: CriticalAddonsOnly
        operator: Exists
  kube-state-metrics:
    namespaceOverride: monitoring
  #
  # The following monitoring features are tmp disabled:
  #
  defaultRules:
    rules:
      etcd: false
      kubeControllerManager: false
      kubeSchedulerAlerting: false
      kubeSchedulerRecording: false
      kubeProxy: false
  kubeEtcd:
    enabled: false
    service:
      enabled: false
  kubeScheduler:
    enabled: false
    service:
      enabled: false
  kubeControllerManager:
    enabled: false
    service:
      enabled: false
  kubeProxy:
    enabled: false
    service:
      enabled: false
```
