### ISSUE TITLE
feature: Cluster/Service CIDR 

### ISSUE THREAD

**Issue by marcinwisniowski** [lablabs/ansible-role-rke2#127]
### Summary

By default RKE2 sets: 
 * 10.42.0.0/16 - for cluster network
 * 10.43.0.0/16 - for service netwotk

In manual installation, those values can be altered with `rke2/config.yaml`:

```
cluster-cidr: 10.1.0.0/16
service-cidr: 10.2.0.0/16
```

The goal is to add a support of `cluster-cidr` and `service-cidr` opinions in this role.

### Issue Type

Feature Idea

**Comment by MonolithProjects** [comment]
Hi @marcinwisniowski, you can achieve that using the variable `rke2_server_options`.

Example:

```yaml
rke2_server_options:
    - "cluster-cidr: 10.1.0.0/16"
    - "service-cidr: 10.2.0.0/16"
```
