### ISSUE TITLE
bug: issues defining custom registry configs after cluster creation

### ISSUE THREAD

**Issue by moray95** [lablabs/ansible-role-rke2#142]
### Summary

Custom registry configs doesn't work without defining a mirror and manually restarting `rke2-agent` on all nodes.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.14.4]
  config file = /Users/moray/.ansible.cfg
  configured module search path = ['/Users/moray/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/7.4.0/libexec/lib/python3.11/site-packages/ansible
  ansible collection location = /Users/moray/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] (/opt/homebrew/Cellar/ansible/7.4.0/libexec/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

### Steps to Reproduce

1. Set up a RKE2 cluster without any registry mirrors or configs.
2. Add a registry config to the existing cluster and rerun the playbook

```yaml
    rke2_custom_registry_configs:
      - endpoint: registry.example.com
        config:
          auth:
            username: "REDACTED"
            password: "REDACTED"
```

3. Add a registry mirror to the existing cluster and rerun the playbook

```yaml
    rke2_custom_registry_mirrors:
      - name: dummy.example.com
        endpoint:
          - https://dummy.example.com
    rke2_custom_registry_configs:
      - endpoint: registry.example.com
        config:
          auth:
            username: "REDACTED"
            password: "REDACTED"
```

4. Restart `rke2-agent` on all nodes

### Expected Results

Stopping at step 2 should be enough to update the registry configuration.

### Actual Results

```console
- Stopping at step 2 doesn't update the registry configs
- Stopping at step 3 produces 401 errors from the registry on image pull
```
