### ISSUE TITLE
feature: kube vip multiple range/CIDR

### ISSUE THREAD

**Issue by M0NsTeRRR** [lablabs/ansible-role-rke2#152]
### Summary

Hello,

Currently `rke2_loadbalancer_ip_range` set `range-global` and we can't add specific subnet to kube-vip.

`rke2_loadbalancer_ip_range` should be a dict like this : 
```yaml
rke2_loadbalancer_ip_range:
  range-global: 192.168.1.50-192.168.1.100
  range-namspeace: 192.168.2.50-192.168.2.100
```

If you agree with the idea I can open a PR

### Issue Type

Feature Idea
