### ISSUE TITLE
Install stuck in "wait for the first server be ready" with kubevip, cilium and kube proxy disabled

### ISSUE THREAD

**Issue by drustan** [lablabs/ansible-role-rke2#157]
### Summary

During the initial installation of a cluster using RKE2 version 1.27.1+rke2r1, kubevip, cilium and kube proxy disabled, the first node is stuck in the NOTREADY state preventing the successful completion of the cluster installation process.

The workaround I found :

- Connect to the first server with SSH
- Manually set the $rke2_api_ip on the network interface `ip a a 192.0.2.20 dev ens224`
- Restart rke2 service `systemctl restart rke2-server.service`

Not sure why this is happening so far, possibly due to the disabling of kube proxy.

### Issue Type

Bug Report

### Ansible Version

```console
Ansible 2.14.8
```

### Steps to Reproduce

Deploy RKE2 with the following variables :

```
rke2_version: v1.27.1+rke2r1
rke2_cluster_group_name: kubernetes_cluster
rke2_servers_group_name: kubernetes_masters
rke2_agents_group_name: kubernetes_workers
rke2_ha_mode: true
rke2_ha_mode_keepalived: false
rke2_ha_mode_kubevip: true
rke2_additional_sans:
  - kubernetes-api.example.net
rke2_api_ip: "192.0.2.20"
rke2_kubevip_svc_enable: false
rke2_interface: "ens224"
rke2_kubevip_cloud_provider_enable: false
rke2_cni: cilium
rke2_disable:
  - rke2-canal
  - rke2-ingress-nginx
rke2_custom_manifests:
  - rke2-cilium-proxy.yaml
disable_kube_proxy: true
rke2_drain_node_during_upgrade: true
rke2_wait_for_all_pods_to_be_ready: true
```
Here is the content of rke2-cilium-proxy.yaml :

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    kubeProxyReplacement: strict
    k8sServiceHost: {{ rke2_api_ip }}
    k8sServicePort: {{ rke2_apiserver_dest_port }}
    ipv4NativeRoutingCIDR: 10.43.0.0/15
    hubble:
      enabled: true
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
      relay:
        enabled: true
        replicas: 3
      ui:
        enabled: true
        replicas: 3
        ingress:
          enabled: false
```

### Expected Results

The first server should at some point be in the READY state, so the installation of the cluster succeed.

### Actual Results

```console
The first server is stuck in the NOTREADY state.
```

**Comment by drustan** [comment]
Until I find the reason for this, so I can identify the appropriate conditions for a patch, I have applied a temporary workaround by integrating it into the pre-tasks of my playbook.

```
---
- hosts: kubernetes_masters
  gather_facts: true
  remote_user: ubuntu
  become: true 

pre_tasks:
    # https://docs.cilium.io/en/v1.13/operations/system_requirements/#systemd-based-distributions
    - name: Do not manage foreign routes
      ansible.builtin.blockinfile:
        path: /etc/systemd/networkd.conf
        insertafter: "^\\[Network\\]"
        block: |
          ManageForeignRoutes=no
          ManageForeignRoutingPolicyRules=no
      register: networkd_patch
    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true
      when: networkd_patch.changed

    # https://github.com/lablabs/ansible-role-rke2/issues/157
    - name: Check if {{ rke2_api_ip }} is pingable
      ansible.builtin.shell: "ping -c 1 {{ rke2_api_ip }}"
      register: ping_result
      ignore_errors: yes
    - name: Add the {{ rke2_api_ip }} address to the first node if no ICMP reply
      ansible.builtin.shell: "ip addr add {{ rke2_api_ip }}/32 dev {{ rke2_interface }}"
      when:
        - ping_result.failed
        - inventory_hostname == groups[rke2_servers_group_name].0

  roles:
    - ansible-role-rke2
```

**Comment by sofronic** [comment]
It's a chicken or the egg scenario. Celium without kube-proxy needs to talk to the kube-api that's being loadbalanced by kube-vip that needs a working cni to contact the kube-api's internal k8s service. As a workaround I set up cilium with:
    k8sServiceHost: rke2 first manager's external ip
And after the cluster is up and running you can change it back to:
    k8sServiceHost: kube-vip ip

**Comment by dtuantran** [comment]
I believe this issue was resolved. I don't have problem with kubevip, cilium and kubeproxy disabled.

**Comment by maxisam** [comment]
> I believe this issue was resolved. I don't have problem with kubevip, cilium and kubeproxy disabled.

not sure if that is possible, i don't see any script is changed for this.

**Comment by happycuban** [comment]
I used @drustan idea

```
- name: Deploy RKE2
  hosts: all
  become: true
  vars:
    rke2_ha_mode: true
    rke2_ha_mode_keepalived: false
    disable_kube_proxy: true
    rke2_cni: cilium
    rke2_disable:
      - rke2-ingress-nginx
      - rke2-canal
    
    rke2_custom_manifests:
      - rke2-cilium-values.yaml

    rke2_drain_node_during_upgrade: true
    rke2_wait_for_all_pods_to_be_ready: true

    rke2_ha_mode_kubevip: true
    rke2_api_ip: xx.xx.xx.xx
    rke2_kubevip_image: ghcr.io/kube-vip/kube-vip:v0.8.9
    rke2_kubevip_ipvs_lb_enable: true
    rke2_kubevip_service_election_enable: true
    
    rke2_kubevip_cloud_provider_enable: false
    rke2_kubevip_svc_enable: false
    
    rke2_additional_sans:
      - k8s-api.domain.local

    rke2_download_kubeconf: true
    rke2_server_node_taints:
      - 'CriticalAddonsOnly=true:NoExecute'
   
  pre_tasks:
    # https://docs.cilium.io/en/v1.13/operations/system_requirements/#systemd-based-distributions
    - name: Do not manage foreign routes
      ansible.builtin.blockinfile:
        path: /etc/systemd/networkd.conf
        insertafter: "^\\[Network\\]"
        block: |
          ManageForeignRoutes=no
          ManageForeignRoutingPolicyRules=no
      register: networkd_patch
      when:
        - rke2_cni == 'cilium'
    
    - name: Force systemd to reread configs
      ansible.builtin.systemd:
        daemon_reload: true
      when:
        - networkd_patch.changed
        - rke2_cni == 'cilium'

    # https://github.com/lablabs/ansible-role-rke2/issues/157
    - name: Check if {{ rke2_api_ip }} is pingable
      ansible.builtin.shell: "ping -c 1 {{ rke2_api_ip }}"
      register: ping_result
      ignore_errors: yes
      when:
        - rke2_cni == 'cilium'
    
    - name: Add the {{ rke2_api_ip }} address to the first node if no ICMP reply
      ansible.builtin.shell: "ip addr add {{ rke2_api_ip }}/32 dev ens192"
      when:
        - rke2_cni == 'cilium'
        - ping_result.failed
        - inventory_hostname == groups[rke2_servers_group_name].0
      register: added_temp_ip
      changed_when: added_temp_ip.rc == 0
  
  
  roles:
    - role: lablabs.rke2


  post_tasks:
    - name: Remove temporary {{ rke2_api_ip }} from first node (enable Kube-VIP HA)
      ansible.builtin.shell: "ip addr del {{ rke2_api_ip }}/32 dev ens192"
      when:
        - rke2_cni == 'cilium'
        - inventory_hostname == groups[rke2_servers_group_name].0
        - added_temp_ip.changed  # Remove IP only if it was added
    
    - name: Check if {{ rke2_api_ip }} is pingable
      ansible.builtin.shell: "ping -c 1 {{ rke2_api_ip }}"
      register: ping_result
      ignore_errors: yes
      when:
        - rke2_cni == 'cilium'
    
    - name: Restore systemd-networkd defaults (Undo ManageForeignRoutes)
      ansible.builtin.replace:
        path: /etc/systemd/networkd.conf
        regexp: '^(ManageForeignRoutes|ManageForeignRoutingPolicyRules)=no'
        replace: '# \1=no  # Removed by Ansible'
      register: networkd_restore
      when:
        - rke2_cni == 'cilium'

    - name: Restart systemd-networkd to apply changes
      ansible.builtin.systemd:
        name: systemd-networkd
        state: restarted
      when:
        - networkd_restore.changed
        - rke2_cni == 'cilium'
```

with rke2-cilium-values.yaml.j2 added to templates 

```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: rke2-cilium
  namespace: kube-system
spec:
  valuesContent: |-
    k8sServiceHost: {{ rke2_api_ip }}
    k8sServicePort: 6443
    kubeProxyReplacement: true
    hubble:
      enabled: true
      metrics:
        enabled:
        - dns:query;ignoreAAAA
        - drop
        - tcp
        - flow
        - icmp
        - http
      relay:
        enabled: true
        replicas: 1
      ui:
        enabled: true
        replicas: 1
        ingress:
          enabled: fals
```

Got three environments with 3 masters and 7 nodes working. Hope it helps or at least inspires at better solution.
