### ISSUE TITLE
bug: Copying of Kube VIP manifests bv 

### ISSUE THREAD

**Issue by lukapetrovic-git** [lablabs/ansible-role-rke2#175]
### Summary

Copying Kube VIP manifests before starting rke2-server on first node #17 introduced a bug, breaks when trying to copy because  _rke2_data_path_/server/manifests (by default /var/lib/rancher/rke2/server/manifests) does not yet exist.

Will create a PR for this fix, simply creating the directory beforehand.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.15.6]
  config file = /home/luka/Documents/repos/dti/infra/infrastructure-ansible/playbooks/linux/kubernetes/ansible.cfg
  configured module search path = ['/home/luka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/luka/Documents/repos/dti/infra/infrastructure-ansible/playbooks/linux/kubernetes
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

### Steps to Reproduce

This task breaks because {{ rke2_data_path }}/server/manifests does not yet exist

```yaml (paste below)
- name: Copy kube-vip files to first server
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "{{ rke2_data_path }}/server/manifests/{{ item | basename | regex_replace('.j2$', '') }}"
    owner: root
    group: root
    mode: 0664
  with_fileglob:
    - "templates/kube-vip/kube-vip.yml.j2"
    - "templates/kube-vip/kube-vip-rbac.yml.j2"
```

### Expected Results

/

### Actual Results

```console
/
```
