### ISSUE TITLE
example hosts file for single host

### ISSUE THREAD

**Issue by kmashwin** [lablabs/ansible-role-rke2#187]
### Summary

I am trying to install rke2 for a single node which acts as server and agent. There is no example how to write the hosts file for a single node cluster.
i took the example for playbook, but can't figure the hosts file for the same.

### Issue Type

Feature Idea

**Comment by jLemmings** [comment]
Could look something like this hosts.yml:

```
---
k8s_cluster:
  children:
    masters:
      hosts:
        192.168.1.[61:63]
      vars:
        rke2_type: server
    workers:
      hosts:
        192.168.1.[71:72]
      vars:
        rke2_type: agent
```
