### ISSUE TITLE
Help a n00b to install in an non internet env..

### ISSUE THREAD

**Issue by sojjan1337** [lablabs/ansible-role-rke2#198]
### Summary

Im sorry, this is not a bug but i can't get it to install. Help needed. I hope someone can point me in the correct direction...

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.16.2]
```

<img width="363" alt="tree" src="https://github.com/lablabs/ansible-role-rke2/assets/44612734/aec28136-03cc-4a36-a277-0163aa9c62d2">

### Steps to Reproduce

```
- name: Deploy RKE2
  hosts: all
  become: yes
  vars:
    rke2_ha_mode: true
    rke2_ha_mode_keepalived: false
    rke2_kubevip_svc_enable: false
    rke2_airgap_mode: true
    rke2_airgap_implementation: copy
    rke2_version: 1.29.1+rke2r1
    rke2_cni:
      - multus
      - calico
    rke2_artifact:
      - sha256sum-{{ rke2_architecture }}.txt
      - rke2.linux-{{ rke2_architecture }}.tar.gz
      - rke2-images.linux-{{ rke2_architecture }}.tar.zst
    rke2_airgap_copy_additional_tarballs:
      - rke2-images-multus.linux-{{ rke2_architecture }}
      - rke2-images-calico.linux-{{ rke2_architecture }}
  roles:
     - role: lablabs

```

### Expected Results

Where do i specify the target dir for my downloaded RKE2 files? Or where should i put the files?
I have a directory with the files: rke2-images.linux-amd64.tar.zst + rke2.linux-amd64.tar.gz + sh256sum-amd64.txt
I'm trying to install in air-gap mode, no internet access. I just want the playbook to install RKE2 on the target nodes in the inventory-file and fetch the files from my directory with the RKE2 files.
We have our own LB.

### Actual Results

```console
I get the following error:
I don't find any rke2.sh file in the role.

TASK [lablabs : Copy local RKE2 installation script] **********************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [master-01]: FAILED! => {"changed": false, "msg": "Could not find or access 'local_artifacts/rke2.sh'\nSearched in:\n\t/home/pingo/Downloads/rke2/roles/lablabs/files/local_artifacts/rke2.sh\n\t/home/pingo/Downloads/rke2/roles/lablabs/local_artifacts/rke2.sh\n\t/home/pingo/Downloads/rke2/roles/lablabs/tasks/files/local_artifacts/rke2.sh\n\t/home/pingo/Downloads/rke2/roles/lablabs/tasks/local_artifacts/rke2.sh\n\t/home/pingo/Downloads/rke2/files/local_artifacts/rke2.sh\n\t/home/pingo/Downloads/rke2/local_artifacts/rke2.sh on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
An exception occurred during task execution.
```
