### ISSUE TITLE
Questions /etc/rancher/rke2/config.yaml

### ISSUE THREAD

**Issue by itscaro** [lablabs/ansible-role-rke2#20]
Hi, Thank you for this role.

I have a question about the generation of this config file `/etc/rancher/rke2/config.yaml`, i'm not sur how, but only the first server node receives the right config with tls-san. Other server nodes contains just:
```
server: https://<keepalived_IP>:9345
token: 
snapshotter: overlayfs
```

So with the rke2.yaml there might be issue with tls due to missing keepalived IP in other server nodes

Do you encounter this issue?

**Comment by MonolithProjects** [comment]
Hi @itscaro. This should not happen. Please check if all your servers are members of the group called `masters`.

**Comment by itscaro** [comment]
I have an inventory like this:
```
    masters:
      hosts:
        controller-01:
        controller-02:
        controller-03:
      vars:
        rke2_type: server
    workers:
      hosts:
        node-01:
        node-02:
        node-03:
        node-04:
      vars:
        rke2_type: agent
    k8s_cluster:
      children:
        masters:
        workers:
```

and playbook like this

```
- hosts: k8s_cluster
  become: true
  vars:
    rke2_ha_mode: true
    rke2_server_taint: true
    rke2_additional_sans:
    - ...
```

the taint is only apply to the first server as well :-/
