### ISSUE TITLE
feature: Solved the problem with `Playbook stuck while starting the RKE2 service on agents` with Debian VMs

### ISSUE THREAD

**Issue by dannyloxavier** [lablabs/ansible-role-rke2#204]
### Summary

Had this problem and workaround it installing podman in all VMs before running the ansible playbook.

Worked flawless.

In my case, my playbook was this one:

```yml
---

- name: Deploy RKE2
  hosts: all
  become: yes
  pre_tasks:
    - name: Install podman
      ansible.builtin.apt:
        name: podman
        state: latest
        update_cache: yes
  roles:
     - role: lablabs.rke2
```

You can try by yourself with this Vagrantfile:

```ruby
#!/usr/bin/env ruby

maquinas = {
  "master-01" => "192.168.56.10/24",
  "worker-01" => "192.168.56.20/24",
  "worker-02" => "192.168.56.21/24",
  "worker-03" => "192.168.56.22/24"
}


Vagrant.configure("2") do |config|
  maquinas.each do |nome, ip|
    config.vm.define nome do |maquina|
      maquina.vm.box = "debian/bookworm64"
      maquina.vm.hostname = "%s" % nome
      maquina.vm.network "private_network", ip: ip, libvirt__network_name: "lab_rke2"
      maquina.vm.provider "libvirt" do |lv|
        lv.memory = 2048
        lv.default_prefix = "lab_rke2_"
      end
    end
    config.nfs.verify_installed = false
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.provision "shell" do |s|
      ssh_pub_key = File.readlines(File.join(Dir.home, ".ssh/id_rsa.pub")).first.strip
      s.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
end
```

and this hosts file:

```ini
[masters]
master-01 ansible_host=192.168.56.10 ansible_user=vagrant rke2_type=server

[workers]
worker-01 ansible_host=192.168.56.20 ansible_user=vagrant rke2_type=agent
worker-02 ansible_host=192.168.56.21 ansible_user=vagrant rke2_type=agent
worker-03 ansible_host=192.168.56.22 ansible_user=vagrant rke2_type=agent

[k8s_cluster:children]
masters
workers
```

### Issue Type

Feature Idea
