### ISSUE TITLE
bug: The "*" wildcard entry cannot be used in the rke2_custom_registry_mirrors section

### ISSUE THREAD

**Issue by jgoelen** [lablabs/ansible-role-rke2#220]
### Summary

We want to pull all images via a private mirror. This should be possible by using a wildcard:

https://docs.k3s.io/installation/private-registry#wildcard-support

The wildcard MUST be quoted when used in the file `/etc/rancher/rke2/registries.yaml`. The latest version of the Jinja template `registries.yaml.j2` doesn't add quotes.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.16.4]
  config file = None
  configured module search path = ['/Users/jgoelen/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/9.3.0/libexec/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/jgoelen/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)] (/opt/homebrew/Cellar/ansible/9.3.0/libexec/bin/python)
  jinja version = 3.1.3
  libyaml = True
```

### Steps to Reproduce

```yaml (paste below)
    rke2_custom_registry_mirrors:
      - name: "*"
        endpoint:
          - "https://registry.internal.org"
    rke2_custom_registry_configs:
      - endpoint: "registry.internal.org"
        config:
          auth:
            username: "{{ registry_user }}"
            password: "{{ registry_password }}"
```

### Expected Results

Successful rollout of the cluster.

### Actual Results
The `rke2-server` service will not start because of the missing quotes in `/etc/rancher/rke2/registries.yaml`:
```yaml
mirrors:
  *:
    endpoint:
      - "https://registry.internal.org"
```
