### ISSUE TITLE
bug: Incorrect indentation on registries config

### ISSUE THREAD

**Issue by Mr-Artemus** [lablabs/ansible-role-rke2#241]
### Summary

Inconsistent YAML indentation in registry template when there are multiple keys (e.g., auth and tls)

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.16.0]
  config file = None
  configured module search path = ['/Users/XXXXX/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXXXX/.local/share/mise/installs/python/3.12.4/lib/python3.12/site-packages/ansible
  ansible collection location = /Users/XXXXX/.ansible/collections:/usr/share/ansible/collections
  executable location = /Users/XXXXX/.local/share/mise/installs/python/latest/bin/ansible
  python version = 3.12.4 (main, Jul 10 2024, 11:12:47) [Clang 15.0.0 (clang-1500.1.0.2.5)] (/Users/XXXXX/.local/share/mise/installs/python/3.12.4/bin/python3.12)
  jinja version = 3.1.4
  libyaml = True
```

### Steps to Reproduce

```yaml
rke2_custom_registry_mirrors:
  - name: "*" # Mirror everything
    endpoint: [ "registry.domain.com" ]
rke2_custom_registry_configs:
  - endpoint: "registry.domain.com"
    config:
      auth:
        username: myaccount
        password: mysupersecretpassword
      tls:
        insecure_skip_verify: true
```

### Expected Results

```yaml
mirrors:
  "*":
    endpoint:
      - "registry.domain.com"
configs:
  registry.domain.com:
    auth:
      password: mysupersecretpassword
      username: myaccount
    tls:
      insecure_skip_verify: true
```

### Actual Results

```console
mirrors:
  "*":
    endpoint:
      - "registry.domain.com"
configs:
  registry.domain.com:
    auth:
      password: mysupersecretpassword
      username: myaccount
tls:
      insecure_skip_verify: true
```
