### ISSUE TITLE
bug: registries.yaml jinja2 template no single backslash

### ISSUE THREAD

**Issue by Raboo** [lablabs/ansible-role-rke2#277]
### Summary

I'm trying to save a  rewrite rule regex with  into /etc/rancher/rke2/registries.yaml with escaped characters using backslash(`\`).

If I single quote or double escape (`\\`), I get a double backslash in registries.yaml (`\\`).
However if I don't escape them or single quote them, Ansible complains:

```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  found unknown escape character. while parsing a quoted scalar
  in "<unicode string>", line 50, column 7
found unknown escape character
  in "<unicode string>", line 50, column 17
```

So seems impossible to send a single backslash to registries.yaml.

However I'm not sure if the regex should be double-escaped in registries.yaml, perhaps it should be double-escaped there as well? But I feel that it shouldn't.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.18.0]
  config file = /virtual-machine-provision/ansible/ansible.cfg
  configured module search path = ['/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/homebrew/Cellar/ansible/11.0.0/libexec/lib/python3.13/site-packages/ansible
  ansible collection location = /virtual-machine-provision/ansible/collections
  executable location = /opt/homebrew/bin/ansible
  python version = 3.13.0 (main, Oct  7 2024, 05:02:14) [Clang 16.0.0 (clang-1600.0.26.3)] (/opt/homebrew/Cellar/ansible/11.0.0/libexec/bin/python)
  jinja version = 3.1.4
  libyaml = True
```

### Steps to Reproduce

```yaml
rke2_custom_registry_mirrors:
  - name: "*"
    endpoint:
      - https://my.registry.com
    rewrite:
      # Matches strings that contain at least one /, capturing:
      # Group 1: The Fully Qualified Domain Name (FQDN) / registry if it exists.
      # Group 2: The word before the first /
      # Group 3: Everything after the first /.
      # ^(?:(?<fqdn>[^/]+\.[^/]+)/)?(?<repo>[^/]+)/(?<image>.+)$ - alternative with group names
      '^(?:([^/]+\.[^/]+)/)?([^/]+)/(.+)$': 'docker-ss-virtual/$2/$3'
      # Matches strings without any /, capturing:
      # Group 1 The entire string
      # ^(?<string>[^/]+)$ - alternative with group names
      '^([^/]+)$': 'docker-ss-virtual/$1'
      '^registry\.rancher\.com/(.*)$': 'docker-rancher-remote/$1'
```

### Expected Results

```yaml
mirrors:
  "*":
    endpoint:
      - "https://my.registry.com"
    rewrite:
      {'^(?:([^/]+\\.[^/]+)/)?([^/]+)/(.+)$': 'docker-ss-virtual/$2/$3', '^([^/]+)$': 'docker-ss-virtual/$1', '^registry\\.rancher\\.com/(.*)$': 'docker-rancher-remote/$1'}
```

### Actual Results

```console
mirrors:
  "*":
    endpoint:
      - "https://my.registry.com"
    rewrite:
      {'^(?:([^/]+\.[^/]+)/)?([^/]+)/(.+)$': 'docker-ss-virtual/$2/$3', '^([^/]+)$': 'docker-ss-virtual/$1', '^registry\.rancher\.com/(.*)$': 'docker-rancher-remote/$1'}
```
