### ISSUE TITLE
bug: Airgab install script not found

### ISSUE THREAD

**Issue by VonNao** [lablabs/ansible-role-rke2#295]
### Summary

During the playbook run the follow error pops up and the playbook is canceled.

`TASK [lablabs.rke2 : Run RKE2 install script with airgap variables] ********************************************************************************************************************************************************************************************
fatal: [kg-c03cp99002t]: FAILED! => {"changed": false, "cmd": "/var/tmp/rke2.sh", "msg": "[Errno 2] No such file or directory: b'/var/tmp/rke2.sh'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}`

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.17.7]
  config file = None
  configured module search path = ['/home/brei430/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/brei430/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/brei430/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/brei430/.local/bin/ansible
  python version = 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Steps to Reproduce

```yaml (paste below)
---
# pinnwand
- name: Install RKE2
  hosts: all
  become: true
  handlers:
    - name: Import handlers
      ansible.builtin.import_tasks: handlers/main.yml

  pre_tasks:
    - name: "Prepare OS for RKE2"
      ansible.builtin.import_tasks: tasks/prepare-host-rke2.yml

  roles:
    - role: lablabs.rke2
      state: present

  tasks:
    - name: "Optain kubeconfig"
      ansible.builtin.import_tasks: tasks/rke2_access.yml
```

### Expected Results

Install script will be placed under /var/tmp/rke2.sh

### Actual Results

```console
`TASK [lablabs.rke2 : Run RKE2 install script with airgap variables] ********************************************************************************************************************************************************************************************
fatal: [kg-c03cp99002t]: FAILED! => {"changed": false, "cmd": "/var/tmp/rke2.sh", "msg": "[Errno 2] No such file or directory: b'/var/tmp/rke2.sh'", "rc": 2, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}`
```
