### ISSUE TITLE
bug: registries.yaml template broken since 1.40.0

### ISSUE THREAD

**Issue by Nold360** [lablabs/ansible-role-rke2#311]
### Summary

The Template for the registries.yaml seems to be broken, since 1.40.0.

### Issue Type

Bug Report

### Ansible Version

```console
N/A
```

### Steps to Reproduce

```yaml (paste below)
rke2_custom_registry_mirrors:
  - name: "{{ kaas_registry }}"
    endpoint:
      - "https://{{ kaas_registry }}"

  - name: rancher.repo
    endpoint:
      - "https://{{ kaas_registry }}"
    rewrite: '"^(.*)": "kaaslight-dockerhub/$1"'

rke2_custom_registry_configs:
  - endpoint: "{{ kaas_registry }}"
    config:
      auth:
        username: "{{ kaas_registry_user }}"
        password: "{{ kaas_registry_password }}"
```

### Expected Results

```yaml
mirrors:
  "kaas-reg.some.domain":
    endpoint:
      - "https://kaas-reg.some.domain"
  "rancher.repo":
    endpoint:
      - "https://kaas-reg.some.domain"
    rewrite:
      "^(.*)": "kaaslight-dockerhub/$1"
configs:
  kaas-reg.some.domain:
    auth:
      password: 1234
      username: user
```

### Actual Results

```console
mirrors:
    "kaas-reg.some.domain":
        endpoint:
            - "https://kaas-reg.some.domain"
                  "rancher.repo":
        endpoint:
            - "https://kaas-reg.some.domain"
                  rewrite:
      "^(.*)": "kaaslight-dockerhub/$1"
      configs:
    kaas-reg.some.domain:
    auth:
      password: 1234
      username: user
```
