### ISSUE TITLE
Rolling restart task not health checking

### ISSUE THREAD

**Issue by jakuzure** [lablabs/ansible-role-rke2#65]
The recently contributed rolling restart task is simply restarting the rke2 service on each node in order, but in my experience the service status being ready in systemd doesn't necessarily mean the node is actually ready and good to go, especially when upgrading master nodes.

I think we should add health checks and only restart the next node once the previous one is confirmed to be up and running again to avoid any potential cluster breakage, at least for the master nodes. This is less serious for worker nodes.

Currently we're using an extra playbook to run these tasks serially, because there isn't a straight forward way to integrate this into the ansible role.

Posting the playbook below for inspiration, maybe somebody has a better idea how to get this into the role. 
Edit: The one minute pause is there, because I noticed that sometimes health checks will work directly after restarting the rke2 service, but then potentially fail for the next few minutes until being ready again

```
---
- name: Restart RKE2 service and check health
  hosts: masters
  become: yes
  serial: 1
  tasks:
    - name: Restart RKE2 server on master nodes
      ansible.builtin.service:
        name: "rke2-server.service"
        state: restarted
    - name: Pause for 1 minute
      pause:
        minutes: 1
    - name: Healthcheck Kube Apiserver
      ansible.builtin.command: curl -k https://localhost:6443/readyz --cert /var/lib/rancher/rke2/server/tls/client-ca.crt --key /var/lib/rancher/rke2/server/tls/client-ca.key
      register: healthcheck_result
      until: healthcheck_result.stdout == 'ok'
      retries: 100
      delay: 5
    - name: Healthcheck RKE2
      ansible.builtin.command: curl -k https://127.0.0.1:9345/v1-rke2/readyz
      register: healthcheck_rke_result
      until: healthcheck_rke_result.rc == 0
      retries: 100
      delay: 5

- name: Restart RKE2 service and check health
  hosts: workers
  become: yes
  serial: "30%"
  tasks:
    - name: Restart RKE2 server on worker nodes
      ansible.builtin.service:
        name: "rke2-agent.service"
        state: restarted
    - name: Pause for 1 minute
      pause:
        minutes: 1
    - name: Healthcheck Kube Apiserver
      ansible.builtin.command: curl -k https://localhost:6443/readyz --cert /var/lib/rancher/rke2/agent/client-kubelet.crt --key /var/lib/rancher/rke2/agent/client-kubelet.key
      register: healthcheck_result
      until: healthcheck_result.stdout == 'ok'
      retries: 100
      delay: 5
```
