### ISSUE TITLE
bug: AIRGAP COPY - multus and calico images not being copied to agent/images path

### ISSUE THREAD

**Issue by miguelgmedina** [lablabs/ansible-role-rke2#90]
### Summary

**Environmental Info:**
RKE2 Version: v1.23.7+rke2r2

Node(s) CPU architecture, OS, and Version: 
Linux master-01 5.4.0-117-generic #132-Ubuntu SMP Thu Jun 2 00:39:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu

Cluster Configuration:
1 master
4 workers
airgap environment
CNI: multus,calico

**Describe the bug:**

When bootstraping RKE2 airgap cluster with CNI plugins other than default (in my case, multus and calico), the CNI images are copied into the `/var/lib/rancher/rke2/artifacts/`. But, in order to deploy CNIs, the tarballs (compressed zst or tar.gz) have to be also copied in `/var/lib/rancher/rke2/agent/images`. 

Please, note that I mentioned the default settings for artifacts and images. 

I already opened an issue for RKE2: https://github.com/rancher/rke2/issues/3147

And the response was that it is the expected behaviour, so the images of the CNIs have to be manually copied to this path.

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.12.6]
  config file = /home/test/ANA/Offline-RKE2-ANA/ansible.cfg
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/test/ANA/Offline-RKE2/collections
  executable location = /home/test/.local/bin/ansible
  python version = 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```

### Steps to Reproduce

```yaml (paste below)
---
- name: RKE2 K8S BOOTSTRAPPING
  hosts: all
  gather_facts: true
  become: true

  vars_files:
    - vars/global.yaml

  vars:
    rke2_ha_mode: false
    rke2_airgap_mode: true
    rke2_airgap_implementation: copy
    rke2_ha_mode_keepalived: false
    rke2_ha_mode_kubevip: false
    rke2_additional_sans:
      - ana.pt
      - k8s.ana.pt
      - k8s-vmware.ana.pt
    rke2_apiserver_dest_port: 6443
    rke_server_taint: true
    rke2_token: GIzY5kxm9WRGxBekiifQ
    rke2_version: v1.23.7+rke2r2
    rke2_channel: stable
    rke2_artifact_path: /var/lib/rancher/rke2/artifacts
    rke2_airgap_copy_sourcepath: local_artifacts/local_artifacts_rke2
    rke2_cni:
      - multus
      - calico
    rke2_download_kubeconf: true
    rke2_download_kubeconf_file_name: rke2.yaml
    rke2_download_kubeconf_path: /tmp
    nexus_container_registry: "{{ nexus_ingress_cr_host }}"
    rke2_custom_registry_mirrors:
      - name: docker.io
        endpoint: 
          - "https://{{ nexus_container_registry }}"
      - name: quay.io
        endpoint: 
          - "https://{{ nexus_container_registry }}"
      - name: docker.elastic.co
        endpoint: 
          - "https://{{ nexus_container_registry }}"
      - name: cr.fluentbit.io
        endpoint:
          - "https://{{ nexus_container_registry }}"
      - name: registry.gitlab.com
        endpoint: 
          - "https://{{ nexus_container_registry }}"
    rke2_custom_registry_configs:
      - endpoint: "\"{{ nexus_container_registry }}\""
        config:
          tls: 
            insecure_skip_verify: true
    rke2_custom_manifests:
      - roles/lablabs.rke2/files/rke2-ingress-nginx-config.yml

    rke2_artifact:
      - sha256sum-{{ rke2_architecture }}.txt
      - rke2.linux-{{ rke2_architecture }}.tar.gz
      - rke2-images.linux-{{ rke2_architecture }}.tar.zst
      - rke2-images-multus.linux-{{ rke2_architecture }}.tar.zst
      - rke2-images-calico.linux-{{ rke2_architecture }}.tar.zst
      
  roles:
    - role: lablabs.rke2
```

### Expected Results

RKE2 nodes in Ready state. 

### Actual Results

```console
First server can't find the multus or calico images. The artifacts files are copied to `{{ rke2_artifact_path: }}` but not to the `agent/images`
```
