### ISSUE TITLE
bug: rke2 config.yaml for server taint

### ISSUE THREAD

**Issue by yaeP0foorovaiRoo** [lablabs/ansible-role-rke2#95]
### Summary

Setting server taint leads to a broken config.yaml. At least for me the task
```
- name: Set server taints
  ansible.builtin.set_fact:
    combined_node_taints: "{{ node_taints}} + [ 'CriticalAddonsOnly=true:NoExecute' ] "
  when: rke2_server_taint and rke2_type == 'server'
```
leads to a broken list in the config.yaml, as the `combined_node_taints` variable ist treated as string instead of list.
The template line in question:
```
{% for taint in combined_node_taints %}
  - {{ taint }}
```

The correct syntax should be:
```
- name: Set server taints
  ansible.builtin.set_fact:
    combined_node_taints: "{{ node_taints + [ 'CriticalAddonsOnly=true:NoExecute' ] }}"
  when: rke2_server_taint and rke2_type == 'server'
```
Both in the task `tasks/first_server.yml` and `vim tasks/remaining_nodes.yml`

I do not understand why this seems to be only a problem for me?

### Issue Type

Bug Report

### Ansible Version

```console
ansible [core 2.13.1]
  config file = None
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/.local/bin/ansible
  python version = 3.9.5 (default, Jun  4 2021, 12:28:51) [GCC 7.5.0]
  jinja version = 3.0.3
  libyaml = True
```

### Steps to Reproduce

Run the playbook with server taint enabled

### Expected Results

in config.yaml:
```
node-taint:
  - CriticalAddonsOnly=true:NoExecute
 ```

### Actual Results

```console
in config.yaml:

node-taint:
  - [
  - ]
  - 
  - [
  - C
  - r
...
 ```
```
